# Generated by Django 4.0.6 on 2022-09-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureapp', '0002_alter_lecture_textbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='textbook',
            field=models.JSONField(default=list, null=True),
        ),
    ]
