# Generated by Django 4.0.6 on 2023-01-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureapp', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answerer',
            field=models.CharField(default='강사', max_length=100),
            preserve_default=False,
        ),
    ]
