# Generated by Django 4.0.6 on 2022-09-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureapp', '0003_alter_lecture_textbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='textbook',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
