# Generated by Django 4.0.6 on 2022-09-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureapp', '0005_alter_coursetime_day_alter_coursetime_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='coursetime',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='CourseTime',
        ),
    ]
