# Generated by Django 4.0.6 on 2022-09-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_student_school'),
        ('lectureapp', '0006_lecture_coursetime_delete_coursetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('test_file', models.FileField(null=True, upload_to='tests/')),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='lectureapp.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testrecords', to='studentapp.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='lectureapp.test')),
            ],
        ),
    ]
