# Generated by Django 4.0.6 on 2022-09-22 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_student_school'),
        ('lectureapp', '0007_test_testrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='lectureapp.lecture'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='studentapp.student'),
        ),
        migrations.AlterField(
            model_name='test',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='lectureapp.lesson'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='lectureapp.lesson')),
            ],
        ),
    ]
