# Generated by Django 4.0.6 on 2022-09-23 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_student_school'),
        ('lectureapp', '0008_alter_courseregistration_lecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.CreateModel(
            name='VideoWatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked', models.IntegerField(blank=True, default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videowatchrecords', to='studentapp.student')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchrecords', to='lectureapp.video')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='lectureapp.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='studentapp.student')),
            ],
        ),
    ]
