# Generated by Django 4.0.6 on 2022-09-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureapp', '0009_video_link_videowatchrecord_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(max_length=250),
        ),
    ]
