# Generated by Django 4.0.6 on 2022-09-23 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureapp', '0010_alter_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_file',
            field=models.FileField(null=True, upload_to='tests/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
