# Generated by Django 4.1.1 on 2022-10-11 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0003_alter_student_school"),
        ("lectureapp", "0011_alter_test_test_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateField()),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolls",
                        to="lectureapp.lecture",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolls",
                        to="studentapp.student",
                    ),
                ),
            ],
            options={"unique_together": {("student", "lecture")},},
        ),
        migrations.DeleteModel(name="CourseRegistration",),
        migrations.AlterField(
            model_name="lecture",
            name="students",
            field=models.ManyToManyField(
                related_name="lectures",
                through="lectureapp.Enroll",
                to="studentapp.student",
            ),
        ),
    ]
