# Generated by Django 4.1.1 on 2022-10-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectureapp", "0012_enroll_delete_courseregistration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
