# Generated by Django 4.1.1 on 2022-10-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectureapp", "0013_alter_lecture_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test", name="name", field=models.CharField(max_length=100),
        ),
    ]
