# Generated by Django 4.1.1 on 2022-10-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectureapp", "0014_alter_test_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
