# Generated by Django 4.1.1 on 2022-11-09 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_student_school'),
        ('lectureapp', '0015_video_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_file',
        ),
        migrations.RemoveField(
            model_name='testrecord',
            name='date',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('lesson', 'student')},
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(upload_to='attachments/')),
                ('size', models.FloatField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='lectureapp.lesson')),
            ],
        ),
    ]
