# Generated by Django 4.1.1 on 2022-11-25 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="올바른 전화번호 양식을 입력해주세요 ex)010-0000-0000",
                                regex="^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$",
                            )
                        ],
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("kor", "국어"),
                            ("math", "수학"),
                            ("eng", "영어"),
                            ("sci", "과학"),
                            ("soc", "사회"),
                            ("ess", "논술"),
                        ],
                        max_length=5,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("account_linked", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name="teacher",
            constraint=models.UniqueConstraint(
                fields=("name", "phone_number"), name="unique_teacher"
            ),
        ),
    ]
