# Generated by Django 4.1.1 on 2023-01-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='account_linked',
        ),
    ]
