# Generated by Django 4.0.6 on 2022-12-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('센텀', '센텀'), ('지곡', '지곡')], default='센텀', max_length=5),
            preserve_default=False,
        ),
    ]
