# Generated by Django 4.1.1 on 2023-01-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_student_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='account_linked',
        ),
    ]
